- name: Configure Linux laptops
  hosts: linux
  gather_facts: true
  become: true
  roles:
    - linux/base # noqa role-name[path]
    - linux/dev-tools # noqa role-name[path]
  tags:
    - linux

# - name: Configure Windoze laptops
#   hosts: windows
#   gather_facts: true
#   become: true
#   tasks:
#     - name: Include Windoze setup roles
#       include_role:
#         name: "windows/{{ item }}"
#       loop:
#         - base
#         - dev-tools
#         - productivity
#         - security
#       tags:
#         - windows
