- name: Install basic development tools.
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - gnupg
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install basic development tools.
  ansible.builtin.dnf:
    name:
      - git
      - curl
      - wget
      - gnupg2
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Terraform task block.
  when: ansible_os_family == "Debian"
  block:
    - name: Ensure unzip is installed
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: Set Terraform version
      ansible.builtin.set_fact:
        terraform_version: "1.12.1" # Move to vars

    - name: Download Terraform archive
      ansible.builtin.get_url:
        url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
        mode: '0644'

    - name: Extract Terraform binary
      ansible.builtin.unarchive:
        src: "/tmp/terraform_{{ terraform_version }}_linux_amd64.zip"
        dest: /usr/local/bin/
        remote_src: true
        mode: '0755'

    - name: Ensure terraform is executable
      ansible.builtin.file:
        path: /usr/local/bin/terraform
        mode: '0755'
        owner: root
        group: root

    - name: Verify terraform install
      ansible.builtin.command: terraform version
      register: terraform_version_check
      changed_when: false

    - name: Print Terraform version
      ansible.builtin.debug:
        var: terraform_version_check.stdout

- name: Terraform task block (Redhat).
  when: ansible_os_family == "RedHat"
  block:
    - name: Add HashiCorp repository.
      ansible.builtin.yum_repository:
        name: hashicorp
        description: HashiCorp Stable - $basearch
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: true
        enabled: true

    - name: Install Terraform.
      ansible.builtin.dnf:
        name: terraform
        state: present

# AWS CLI v2 installation
- name: Download AWS CLI installer (Debian family)
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'
  when: ansible_os_family == "Debian"

- name: Extract AWS CLI installer (Debian family)
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: true
  when: ansible_os_family == "Debian"

- name: Install AWS CLI v2 (Debian family)
  ansible.builtin.command: /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws
  when: ansible_os_family == "Debian"

- name: Install AWS CLI v2 (RedHat family)
  ansible.builtin.dnf:
    name: awscli
    state: present
  when: ansible_os_family == "RedHat"

# Docker installation (Debian)
- name: Docker installation.
  when: ansible_os_family == "Debian"
  block:
    - name: Create apt keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key (Debian family)
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository (Debian family)
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker (Debian family)
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

# Docker installation (RedHat)
- name: Docker installation.
  when: ansible_os_family == "RedHat"
  block:
    - name: Add Docker repository (RedHat family)
      ansible.builtin.yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: true
        enabled: true

    - name: Install Docker (RedHat family)
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
