- name: Install basic development tools.
  apt:
    name:
      - git
      - curl
      - wget
      - gnupg
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install basic development tools.
  dnf:
    name:
      - git
      - curl
      - wget
      - gnupg2
      - python3
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

# Terraform installation
- name: Terraform task block (Debian).
  when: ansible_os_family == "Debian"
  block:
    - name: Add HashiCorp GPG key.
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    - name: Add HashiCorp repository.
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Install Terraform.
      apt:
        name: terraform
        state: present
        update_cache: yes

- name: Terraform task block (Redhat).
  when: ansible_os_family == "RedHat"
  block:
    - name: Add HashiCorp repository.
      yum_repository:
        name: hashicorp
        description: HashiCorp Stable - $basearch
        baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
        gpgkey: https://rpm.releases.hashicorp.com/gpg
        gpgcheck: yes
        enabled: yes

    - name: Install Terraform.
      dnf:
        name: terraform
        state: present

# AWS CLI v2 installation
- name: Download AWS CLI installer (Debian family)
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
  when: ansible_os_family == "Debian"

- name: Extract AWS CLI installer (Debian family)
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes
  when: ansible_os_family == "Debian"

- name: Install AWS CLI v2 (Debian family)
  command: /tmp/aws/install --update
  become: yes
  args:
    creates: /usr/local/bin/aws
  when: ansible_os_family == "Debian"

- name: Install AWS CLI v2 (RedHat family)
  dnf:
    name: awscli
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

# Docker installation (Debian)
- name: Docker installation.
  when: ansible_os_family == "Debian"
  block:
    - name: Create apt keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG key (Debian family)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository (Debian family)
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker (Debian family)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

# Docker installation (RedHat)
- name: Docker installation.
  when: ansible_os_family == "RedHat"
  block:
    - name: Add Docker repository (RedHat family)
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
        gpgkey: https://download.docker.com/linux/centos/gpg
        gpgcheck: yes
        enabled: yes

    - name: Install Docker (RedHat family)
      dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
